services:
  app:
    image: ghcr.io/anbuchelva/vnstat-dashboard:latest
    container_name: vnstat-dashboard
    ports:
      - '8678:8678'
    volumes:
      - .app/config.py:/app/config.py
      - /var/lib/vnstat/vnstat.db:/var/lib/vnstat/vnstat.db
